import datetime
from gql import gql, Client
from gql.transport.requests import RequestsHTTPTransport

def send_order_reminders():
    # Calculate date 7 days ago
    seven_days_ago = datetime.date.today() - datetime.timedelta(days=7)
    date_str = seven_days_ago.isoformat()

    # Configure the transport with the URL of the GraphQL endpoint
    transport = RequestsHTTPTransport(
        url='http://localhost:8000/graphql',
        verify=False,
        retries=3,
    )

    # Create a GraphQL client using the defined transport
    # fetch_schema_from_transport=False allows the script to define the query without fetching the full schema
    client = Client(transport=transport, fetch_schema_from_transport=False)

    # Define the GraphQL query to fetch orders within the last week
    # Assuming 'orderDate_After' is the filter generated by DateFromToRangeFilter for 'order_date'
    query = gql("""
    query GetPendingOrders($date: Date) {
      allOrders(orderDate_After: $date) {
        edges {
          node {
            id
            orderDate
            customer {
              email
            }
          }
        }
      }
    }
    """)

    try:
        # Execute the query
        result = client.execute(query, variable_values={"date": date_str})
        
        orders = result.get('allOrders', {}).get('edges', [])
        
        # Log each order's ID and customer email
        with open('/tmp/order_reminders_log.txt', 'a') as f:
            for edge in orders:
                node = edge['node']
                order_id = node['id']
                email = node['customer']['email']
                timestamp = datetime.datetime.now().isoformat()
                f.write(f"{timestamp}, Order ID: {order_id}, Customer Email: {email}\n")
        
        print("Order reminders processed!")

    except Exception as e:
        # In a real scenario, you might want to log this error too
        print(f"Error processing reminders: {e}")

if __name__ == "__main__":
    send_order_reminders()
